version: '3.8'

services:
  door-access:
    build: .
    container_name: door-access
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/dooraccess
    restart: unless-stopped
    networks:
      - door-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - door-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  door-network:
    driver: bridge
