version: '3.8'

services:
  door-access:
    build: .
    container_name: door-access
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/dooraccess
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-1234}
    restart: always
    networks:
      - door-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /root/storage/nongodb/db:/data/db
      - /root/storage/nongodb/config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - door-network
    restart: always
    command: mongod --bind_ip 0.0.0.0


networks:
  door-network:
    name: door-access-network
    driver: bridge
