version: '3.8'

services:
  door-access:
    build: .
    container_name: door-access
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/dooraccess
    restart: always
    networks:
      - door-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - door-network
    restart: always
    command: mongod --bind_ip 0.0.0.0

volumes:
  mongodb_data:
    name: door-access-mongodb-data
  mongodb_config:
    name: door-access-mongodb-config

networks:
  door-network:
    name: door-access-network
    driver: bridge
